"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from core.config import resolve_django_db_path

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'clients',
    'context',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Before anything that can return a response, so browser preflights get CORS headers.
    'corsheaders.middleware.CorsMiddleware',
    # Serves collected static files (the admin's CSS/JS) when DEBUG is off.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

REPO_ROOT = BASE_DIR.parent

if sys.argv[1:2] == ['test']:
    # Tests run on local SQLite only, never the hosted database from .env. Cleared from the
    # environment so core, running in this same process, follows too.
    os.environ.pop('DATABASE_URL', None)
    os.environ.pop('CONTEXTKIT_HOSTED', None)


def database_settings(url):
    """One hosted Postgres database for core and Django (ADR 026), else the local SQLite file."""
    if url:
        import dj_database_url

        return dj_database_url.parse(url, conn_max_age=60, ssl_require=True)
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        # Django's own file (clients, api_keys, auth), separate from core's database. Core's
        # resolver is used so core reads keys from exactly this file.
        'NAME': resolve_django_db_path(),
        # A file, not in-memory, so core's read-only connection can see test clients too.
        'TEST': {'NAME': str(REPO_ROOT / 'test_django.sqlite3')},
    }


DATABASES = {'default': database_settings(os.getenv('DATABASE_URL', '').strip())}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# User API (ADR 028). Views set their own authentication; these are the JWT and
# throttling settings they use.
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES': {
        # Login and refresh, per client IP.
        'auth': os.getenv('DJANGO_AUTH_THROTTLE_RATE', '10/min'),
    },
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'UPDATE_LAST_LOGIN': True,
}

# The website calls the user API from another origin. JWTs travel in the Authorization
# header, never cookies, so credentials stay off; only /api/v1/ is cross-origin.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('DJANGO_CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
CORS_URLS_REGEX = r'^/api/v1/.*$'

# Deployment behind a reverse proxy; set these from the deployment environment.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if os.getenv('DJANGO_BEHIND_PROXY', 'False').lower() == 'true':
    # Only behind a proxy that always sets X-Forwarded-Proto; otherwise clients could spoof it.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
